### ISSUE TITLE
Uncaught Invariant Violation: Ensemble(...): Nothing was returned from render.

### ISSUE THREAD

**Issue by xinyuewang1** [xinyuewang1/simple-wear#18]
```
 This usually means a return statement is missing. Or, to render nothing, return null.
    at http://localhost:3000/static/js/1.chunk.js:28766:40
    at reconcileChildFibers (http://localhost:3000/static/js/1.chunk.js:28769:19)
    at reconcileChildren (http://localhost:3000/static/js/1.chunk.js:30875:32)
    at mountIndeterminateComponent (http://localhost:3000/static/js/1.chunk.js:31614:9)
    at beginWork$1 (http://localhost:3000/static/js/1.chunk.js:32775:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/1.chunk.js:13781:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/1.chunk.js:13830:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/1.chunk.js:13884:35)
    at beginWork$$1 (http://localhost:3000/static/js/1.chunk.js:37988:11)
    at performUnitOfWork (http://localhost:3000/static/js/1.chunk.js:36920:16)
    at workLoopSync (http://localhost:3000/static/js/1.chunk.js:36898:26)
    at renderRoot (http://localhost:3000/static/js/1.chunk.js:36573:15)
    at runRootCallback (http://localhost:3000/static/js/1.chunk.js:36227:24)
    at http://localhost:3000/static/js/1.chunk.js:25304:28
    at unstable_runWithPriority (http://localhost:3000/static/js/1.chunk.js:47771:16)
    at runWithPriority$2 (http://localhost:3000/static/js/1.chunk.js:25252:14)
    at flushSyncCallbackQueueImpl (http://localhost:3000/static/js/1.chunk.js:25299:11)
    at flushSyncCallbackQueue (http://localhost:3000/static/js/1.chunk.js:25287:7)
    at scheduleUpdateOnFiber (http://localhost:3000/static/js/1.chunk.js:36085:13)
    at dispatchAction (http://localhost:3000/static/js/1.chunk.js:29960:9)
    at getTemp (http://localhost:3000/static/js/main.chunk.js:2347:13)
```

**Comment by xinyuewang1** [comment]
It looks like could be the logic to decide hours will potentially cause this problem, but can't reproduce it for now. We'll see later.
